Preserve data
M-AminAlizadeh/School-library pull request #6
Opened 2023-10-11 19:44 UTC by M-AminAlizadeh

The things that we did in this PR:

- On startup of the app load all data from files
- On exit from the app save all the data (books, people, and rentals) into JSON files

2023-10-11 20:18 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Good descriptive README file 👍🏽

## Required Changes ♻️
_Check the comments under the review._

I am leaving the review feedback here because I couldn't find the file changes in the specific areas where things are not working as expected. Kindly work on the changes mentioned here and resubmit for review 👍🏽 

- [ ] When creating a person, the app keeps asking for the creation of a person repeatedly. It's expected that, after creating either a student or a teacher, the creation completes and then brings the initial options for other features. Kindly fix that so the option for creating a person does not keep looping infinitely 👍🏽

<img width="1226" alt="Screenshot 2023-10-11 at 8 06 35 PM" src="https://github.com/M-AminAlizadeh/School-library/assets/50941074/18b30f41-a6c9-45c3-a5c4-9c2806f0f3e3">

- [ ] I tried creating a book and the app crashed with the error shown in the screenshot below. Kindly work on that so a book can be created successfully 👍🏽

<img width="1205" alt="Screenshot 2023-10-11 at 8 05 09 PM" src="https://github.com/M-AminAlizadeh/School-library/assets/50941074/29c21fcc-9b57-4b5a-b185-ceed40cd7776">

- [ ] I am unable to check if data is stored as expected because the app is not working as expected for data to be stored in separate JSON files as expected. Kindly fix the issues mentioned above so all features work fine and data is preserved as expected 👍🏽

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-10-12 08:44 UTC, shella12 requested changes
Hi @M-AminAlizadeh, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Data is preserved in `json` format ✅ 
- Console app is working as expected ✅   

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 08:44 UTC, shella12 commented on rentals.json
- [ ] Great job on working on the changes requested by the previous reviewer. The data presevation feature ia working well for books and person however when we exit the app rental is not being saved and is causing an error. Please try to fix the error and see the screenshot for error details:

<img width="799" alt="Screenshot 2023-10-12 at 1 38 25 PM" src="https://github.com/M-AminAlizadeh/School-library/assets/44798044/9e212b84-10eb-4261-a2fe-0b043f709349">

2023-10-12 09:06 UTC, M-AminAlizadeh commented on rentals.json
@shella12 Thank you for the review
Yes I missed this one

2023-10-12 09:29 UTC, Munsa1 approved these changes
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 
App Works As Expected :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 09:30 UTC, merged